name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r vote/requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;

      - name: Create Bundle Code
        run: |
          zip -r bundle.zip .

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: python-bundle
          path: bundle.zip

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release test
