name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r vote/requirements.txt

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: "flake8_py3"

      - name: Create Bundle Code
        run: |
          zip -r bundle.zip .

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: python-bundle
          path: bundle.zip
